services:

  OxidCommunity\GraphQl\Dao\CategoryDaoInterface:
    class: OxidCommunity\GraphQl\Dao\CategoryDao
    public: false
    autowire: true

  OxidCommunity\GraphQl\Type\ObjectType\CategoryType:
    class: OxidCommunity\GraphQl\Type\ObjectType\CategoryType
    public: false
    autowire: true

  OxidCommunity\GraphQl\Type\Provider\CategoryProvider:
    class: OxidCommunity\GraphQl\Type\Provider\CategoryProvider
    public: false
    autowire: true
    tags:
      - {name: 'graphql_query_provider'}
      - {name: 'graphql_mutation_provider'}

  OxidCommunity\GraphQl\Service\CategoryPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    public: false
    autowire: true
    calls:
      - ['addPermission', ['admin', 'mayaddcategory']]
      - ['addPermission', ['shopadmin', 'mayaddcategory']]
      - ['addPermission', ['admin', 'mayreaddata']]
      - ['addPermission', ['shopadmin', 'mayreaddata']]
    tags:
      - {name: 'graphql_permissions_provider'}