services:

  OxidProfessionalServices\GraphQl\Custom\Dao\LocationDaoInterface:
    class: OxidProfessionalServices\GraphQl\Custom\Dao\LocationDao
    public: false
    autowire: true

  OxidProfessionalServices\GraphQl\Custom\Type\ObjectType\LocationType:
    class: OxidProfessionalServices\GraphQl\Custom\Type\ObjectType\LocationType
    public: false
    autowire: true

  OxidProfessionalServices\GraphQl\Custom\Type\Provider\LocationProvider:
    class: OxidProfessionalServices\GraphQl\Custom\Type\Provider\LocationProvider
    public: false
    autowire: true
    tags:
      - {name: 'graphql_query_provider'}
      - {name: 'graphql_mutation_provider'}

  OxidProfessionalServices\GraphQl\Custom\Service\LocationPermissionsProvider:
    class: OxidEsales\GraphQl\Service\PermissionsProvider
    public: false
    autowire: true
    calls:
      - ['addPermission', ['admin', 'mayaddlocation']]
      - ['addPermission', ['shopadmin', 'mayaddlocation']]
      - ['addPermission', ['admin', 'mayreaddata']]
      - ['addPermission', ['shopadmin', 'mayreaddata']]
    tags:
      - {name: 'graphql_permissions_provider'}
